
=head1 GPSClipper for Android

In one step, update with GEOTAGS each photo in an on-line web album using latitude/longitude data from a file stored on the phone. 

=head1 DESCRIPTION

For those using cameras without built-in GPS, integrated GPS can be approximated by using android phone's apps such as 
B<MyTracks> to record data while the photos are being taken. Once the photos have been uploaded to either Picasa or to G+, run the app on the phone, selecting the album and the GPS data and all the on-line photos will have GPS data applied to them. 

=head2 Feature List

=over 4

=item * This is a bulleted list.

=item * Here's another item.

=back

=begin html

<a href="http://www.youtube.com/watch?v=Je_5P5MPS98"><img src="http://lh5.ggpht.com/wP-jH66rvb-KMKvv8_deQ4fFVdTslR92iDy015dQbIInQGDvt7aqhr81R6wGe42a7b7W"></a>
<p>
    Select an album from your online list as you see above.

Select a gpx file from your phone.
</p>
=end html

